### ISSUE TITLE
Puppet gem v5.3.4 breaks spec tests

### ISSUE THREAD

**Issue by LMacchi** [dylanratcliffe/onceover#152]
Leaving this here in case it helps someone.

Puppet 5.3.4 changed an internal Puppet library, so running spec tests with onceover results in the following error:

```
Failures:
  1) role::ci using fact set CentOS-7.0-64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
     
     TypeError:
       no implicit conversion of nil into String
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/module.rb:316:in `join'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/module.rb:316:in `has_translations?'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:12:in `block in load_from_modulepath'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:11:in `each'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/gettext/module_translations.rb:11:in `load_from_modulepath'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/node/environment.rb:444:in `use_text_domain'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/indirector/catalog/compiler.rb:52:in `find'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/puppet-5.3.4/lib/puppet/indirector/indirection.rb:198:in `find'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:83:in `catalog'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:161:in `catalog'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:354:in `build_catalog_without_cache'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:375:in `block in build_catalog'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/cache.rb:17:in `get'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:374:in `build_catalog'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:75:in `block in load_catalogue'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:319:in `with_vardir'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:69:in `load_catalogue'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:10:in `block in subject'
     # /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-puppet-2.6.9/lib/rspec-puppet/matchers/compile.rb:23:in `matches?'
     # ./spec/classes/role__ci_on_CentOS-7.0-64_spec.rb:23:in `block (3 levels) in <top (required)>'
```

Workaround is to not use Puppet gem v5.3.4.

v5.3.3, v5.3.5 and v5.4.0 do not have this issue.
