### ISSUE TITLE
Onceover run spec ignores node names in factsets

### ISSUE THREAD

**Issue by witchbutter** [dylanratcliffe/onceover#168]
I cannot get onceover run spec to run any meaningful test no matter what I do.  I am testing against hiera 5 and no matter what I do it always fails everything against a 'node_name' which is the local hostname.  I have created custom factsets which are complete copies of the output of puppet facts on running servers and added every possible permutation of trusted facts which might replace the node name during the spec run and I am stuck with the same error every time:
```
  1) roles::produbuntuvsphere using fact set server-01.somedomain.net should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
       error during compilation: Function lookup() did not find a value for the name 'node::location' on node laptop.somedomain.com
     # ./spec/classes/roles__produbuntuvsphere_on_server-01.somedomain.net_spec.rb:10:in `block (3 levels) in <top (required)>'
```
I believe hiera to be working because it is searching for a variable node::location, but I really have no way to confirm this since there is no meaningful error message and seemingly no way to override hiera.

My hiera.yaml is generic and is sitting in the spec directory as indicated in the docs:
```
---
version: 5
defaults:
  datadir: "../data"
  data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    globs:
      - "nodes/%{environment}/%{::trusted.certname}.yaml"
      - "services/%{environment}/*.yaml"
      - "common.yaml"
    lookup_key: eyaml_lookup_key
    options:
      pkcs7_private_key: /opt/puppetlabs/puppet/keys/private_key.pkcs7.pem
      pkcs7_public_key: /opt/puppetlabs/puppet/keys/public_key.pkcs7.pem
```

**Comment by dylanratcliffe** [comment]
Hey @witchbutter I've updated the README to make this a bit more clear: https://github.com/dylanratcliffe/onceover#hiera-eyaml. Usually I would recommend that for testing purposes you totally remove the eyaml backend. That means your `hiera.yaml` will look like this:

```yaml
---
version: 5
defaults:
  datadir: "../data"
  data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    globs:
      - "nodes/%{environment}/%{::trusted.certname}.yaml"
      - "services/%{environment}/*.yaml"
      - "common.yaml"
```

Also please note that usage of trusted facts was only added in #163 and released in v3.6.0

Please let me know if that works and if I should clarify the README any more

**Comment by EpicPhil** [comment]
Are you only using the onceover factsets and roles in onceover.yaml for testing or are you writing additional puppet-rspec tests for your roles and profiles?

I'm using both and ran into this issue with the puppet-rspec tests where it was always using the local node name instead of whatever I was supplying in ```let(:facts)```. The solution was to specify the node symbol. E.g.: ```let(:node) { 'server.example.com' }```

**Comment by witchbutter** [comment]
I have collected all the factsets using `puppet facts` on running servers.  I have defined all nodes and factsets in onceover.yaml.  Since I was only using `onceover run spec` and not writing additional specs I don't think there is a place for me to write let statements?

**Comment by witchbutter** [comment]
```
require 'spec_helper'

describe "roles::serverone" do

  context "using fact set serverone-01.prod.domain.net" do
  	node_facts {...really long list of custom facts...}
    let(:facts) { node_facts }
    it { should compile }
  end
end
```
So I see when onceover runs it automatically builds a _spec.rb file for every node I have defined in onceover.yaml as shown above.  The problem is that it isn't including a let(:node) section that would probably fix this.  If I manually add let(:node) to the resultant spec files the next time I run onceover run spec it erases all my changes.  How do I change whatever template is generating this to include the node name?

**Comment by witchbutter** [comment]
After a lot of trial and error, the problem is hiera.  The docs indicate that hiera-eyaml should be removed and as long as you have a hiera.yaml file in the spec directory should work.  This is actually not true.

```
 ---
version: 5
defaults:
  datadir: data
  data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    globs:
      - "nodes/%{environment}/local/%{::trusted.certname}.yaml"
      - "services/%{environment}/*.yaml"
      - "common.yaml"
```
The above hiera.yaml hierarchy definition, which is a typical starting hiera.yaml for a real control repo,  fails for two reasons.  One) the testing hiera.yaml file is in spec and doesn't have a folder named data.  Two) onceover is not able to interpolate any variables, even if you add a 'trusted' stanza in your factsets containing the trusted.certname.

```
---
version: 5
defaults:
  datadir: "../data"
  data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    globs:
      - "nodes/production/local/*.yaml"
      - "services/production/*.yaml"
      - "common.yaml"
```
The above hiera.yaml file works, although it creates a situation where you could get a wrong first match of hiera key because it's scanning every individual host yaml file that could have an override in it.
