### ISSUE TITLE
Difficulty with Hiera-eyaml, Factsets, and Automatic Class Parameters

### ISSUE THREAD

**Issue by EpicPhil** [dylanratcliffe/onceover#171]
I'm having difficulty troubleshooting my onceover setup for a new control-repo. We are using hiera-eyaml, which should pass data to the catalog depending on a trusted fact. The data should be passed into the class via automatic parameter lookup with hiera. I believe this is an issue with how I'm referencing hiera with onceover, as this works correctly when deployed to a node.

The error produced by the spec test is
```
1) role::base_application using fact set Win-2016-Domain1 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }

       error during compilation: Evaluation Error: Error while evaluating a Function Call, Class[Profile::Base::Windows::Domainjoin]:
         expects a value for parameter 'ad_join_username'
         expects a value for parameter 'ad_join_password' (file: C:/Users/redacted/Source/Workspaces/redacted/control-repo/.onceover/etc/puppetlabs/code/environments/production/site/profile/manifests/base.pp, line: 15, column: 9) on node mylaptop.domain.local
     # ./spec/classes/role__base_application_on_Win-2016-Doamin1_spec.rb:10:in `block (3 levels) in <top (required)>'
```

/spec/hiera.yaml
```yaml
---
version: 5
defaults:
  datadir: data
  data_hash: yaml_data
hierarchy:
  - name: 'Yaml backend'
    paths:
      - "nodes/%{trusted.certname}.yaml"
      - "domains/%{trusted.extensions.pp_zone}.yaml"
      - 'common.yaml'
```

/spec/onceover.yaml
```yaml
---
classes:
  - /^role::base/
nodes:
  - Win-2016-Domain1
class_groups:
  windows_roles:
    - role::base_application
    - role::base_webserver
node_groups:
  windows_nodes:
    - /^Win/
  non_windows_nodes:
    include: 'all_nodes'
    exclude: 'windows_nodes'

test_matrix:
  - Win-2016-Domain1:
      classes: 'role::base_application'
      tests: 'spec'
```
/data/domains/domain1.yaml
```yaml
---
profile::base::windows::domainjoin::username: 'service account'
profile::base::windows::domainjoin::password: <eyaml encoded data>
```
/spec/factsets/Win-2016-Domain1.json
```json
{
  "name": "server.domain.local",
  "trusted": {
    "pp_zone": "domain1"
  }
}
```
With these files, onceover should be pulling the facts for spec/factsets/Win-2016-Domain1.json to build the catalog. It should then detect the trusted fact pp_zone and use the hiera data in /data/domains/domain1.yaml, which includes specifications for the class parameters, correct?
