### ISSUE TITLE
does node_groups key accept regular expressions

### ISSUE THREAD

**Issue by ndelic0** [dylanratcliffe/onceover#312]
```
# supported nodes
nodes:
  - foo-dev-server
  - foo-staging-server
  - foo-prod-server
  - bar-dev-server
  - bar-staging-server
  - bar-prod-server
  
  node_groups:
    foo_group:
      - /^foo/
    bar_group:
      - /^bar/
      
  class_groups:
    foo_roles:
      - '/^role::foo/'
    bar_roles:
      - '/^role::bar/'
```
Expecting that foo_group contain foo server definitions. Getting empty set.  Tests are run only if node group members are explicitly defined

```
node_group:
  foo_group:
    - foo-dev-server
    - foo-staging-server
    - foo-prod-server
```
