### ISSUE TITLE
Allow include and exclude to take an array of groups

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#58]
It'd be able to be able to build a group based on multiple other groups, eg 

```yaml
class_groups:
  windows_roles:
    - role::something_windows
  linux_roles:
    - role::something_linux
  general_roles:
    include: 'all_classes'
    exclude: 
      - 'windows_roles'
      - 'linux_roles'
```
